name: drago_pos_printer_example
description: Demonstrates how to use the drago_pos_printer plugin.
publish_to: 'none'

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  drago_pos_printer:
    path: ../
  cupertino_icons: ^1.0.2
  webcontent_converter:
    git:
      url: https://github.com/selvam920/webcontent_converter
  charset_converter:
  intl:
  path_provider:
  printing:
  pdf:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
