name: drago_pos_printer
description: flutter package for print or list down both wireless and bluetooth esc printer devices.
version: 0.0.4
homepage: https://github.com/selvam920/drago_pos_printer

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  hex: ^0.2.0
  image: ^4.0.15
  drago_blue_printer: ^0.0.3
  drago_usb_printer: ^0.0.2
  network_info_plus: ^3.0.2
  printing: ^5.10.1
  win32: ^4.1.1
  ffi: ^2.0.1
  gbk_codec: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.drago_pos_printer
        pluginClass: DragoPosPrinterPlugin
      ios:
        pluginClass: DragoPosPrinterPlugin
      linux:
        pluginClass: DragoPosPrinterPlugin
      macos:
        pluginClass: DragoPosPrinterPlugin
      windows:
        pluginClass: DragoPosPrinterPlugin
      web:
        pluginClass: DragoPrinterManager
        fileName: drago_pos_printer.dart

